name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    if: github.repository == 'it-diots/it-diots'
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: it-diots
          squash-commits: true
          changelog-types: |
            [
              {"type":"chore","section":"Other Changes","hidden":false},
              {"type":"build","section":"Build","hidden":true},
              {"type":"docs","section":"Documentation","hidden":false},
              {"type":"feat","section":"Features","hidden":false},
              {"type":"fix","section":"Bug Fixes","hidden":false},
              {"type":"style","section":"Styles","hidden":false},
              {"type":"refactor","section":"Code Refactoring","hidden":false},
              {"type":"style","section":"Style","hidden":false},
              {"type":"test","section":"Tests","hidden":false},
              {"type":"perf","section":"Performance Improvements","hidden":false},
              {"type":"ci","section":"Continuous Integration","hidden":false},
              {"type":"revert","section":"Reverts","hidden":false}
            ]
          token: ${{ secrets.GH_TOKEN }}
